export const siteUrl = 'https://rowstocrm.com';
export const contactEmail = 'hello@rowstocrm.com';
export const privacyEmail = 'privacy@rowstocrm.com';
export const demoBookingUrl = 'https://zcal.co/rowstocrm/demo';
export const demoBookingFallbackUrl = `mailto:${contactEmail}?subject=RowsToCRM%20demo%20request`;
export const bookingUrl = demoBookingUrl || demoBookingFallbackUrl;
export const isExternalBookingUrl = bookingUrl.startsWith('http');
export const termsUrl = '/terms';
export const privacyUrl = '/privacy';
export const cookiePolicyUrl = '/cookie-policy';
export const ogImageUrl = `${siteUrl}/og-image.svg`;
